networks:
  fabric-network:
    driver: bridge
    name: fabric-network

services:
  initializer_yachtsales:
    networks:
      - fabric-network
    build:
      context: ./Yacht_Sales
      dockerfile: Dockerfile
    image: yfw-yachtsales-ca:latest
    container_name: container-initializer-yachtsales-ca
    hostname: yachtsales
    ports:
      - "9054:9054"
    volumes:
      - ./Yacht_Sales/crypto/:/etc/hyperledger/
      - ./_scripts/:/etc/scripts/
    environment:
      - FABRIC_CA_SERVER_PORT=9054
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/server/tls-ca
      - FABRIC_CA_SERVER_TLS_CLIENTAUTH_TYPE=NoClientCert
    command: >
      bash -c "
      echo 'Starting Fabric TLS CA server...';
      fabric-ca-server start -b tlsadmin:tlsadminpw & 
      sleep 3;
      echo 'Running enroll-tls.sh...';
      ./enroll-tls-new.sh;
      echo 'Initializer completed.'"
    restart: "no"

  yachtsales-ca:
    networks:
      - fabric-network
    build:
      context: ./Yacht_Sales
      dockerfile: Dockerfile
    image: yfw-yachtsales-ca:latest
    container_name: yachtsales-ca
    hostname: yachtsales
    ports:
      - "9054:9054"
    volumes:
      - ./Yacht_Sales/crypto/:/etc/hyperledger/
      - ./_scripts/:/etc/scripts/
      - ./_shared_certs/:/etc/_shared_certs/
      - ./Yacht_Sales/_env/:/etc/_env/

    depends_on:
      initializer_yachtsales:
        condition: service_completed_successfully
    environment:
      - FABRIC_CA_SERVER_PORT=9054
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/server/ca
      - FABRIC_CA_SERVER_TLS_CLIENTAUTH_TYPE=RequireAndVerifyClientCert
    command: >
      bash -c "
      echo 'Starting Fabric ORG CA server...';
      fabric-ca-server start -b admin:adminpw &
      sleep 3;
      echo 'Running enroll-ca.sh...';
      ./enroll-ca-new.sh;
      wait;
      if [ -f /etc/_env/env ]; then
        source /etc/_env/env && fabric-ca-server start;
      else
        echo 'Env file not found!';
        exit 1;
      fi"